name: Build Soi's Tetris (one-file workflow)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Android 프로젝트 파일 생성
      - name: Write Android project files
        shell: bash
        run: |
          set -e
          mkdir -p app/src/main/java/com/soi/tetris
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/res/mipmap-anydpi-v26

          cat > settings.gradle.kts <<'EOF'
          rootProject.name = "SoiTetris"
          include(":app")
          EOF

          cat > build.gradle.kts <<'EOF'
          plugins {
              id("com.android
