name: Build Soi's Tetris (one-file workflow)

on:
  workflow_dispatch:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) Android 프로젝트 파일 생성
      - name: Write Android project files
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p app/src/main/java/com/soi/tetris
          mkdir -p app/src/main/res/layout
          mkdir -p app/src/main/res/values
          mkdir -p app/src/main/res/mipmap-anydpi-v26

          cat > settings.gradle.kts <<'EOF'
          rootProject.name = "SoiTetris"
          include(":app")
          EOF

          cat > build.gradle.kts <<'EOF'
          plugins {
              id("com.android.application") version "8.5.2" apply false
              id("org.jetbrains.kotlin.android") version "1.9.24" apply false
          }
          EOF

          cat > app/build.gradle.kts <<'EOF'
          plugins {
              id("com.android.application")
              id("org.jetbrains.kotlin.android")
          }

          android {
              namespace = "com.soi.tetris"
              compileSdk = 34

              defaultConfig {
                  applicationId = "com.soi.tetris"
                  minSdk = 24
                  targetSdk = 34
                  versionCode = 1
                  versionName = "1.0"
              }

              buildTypes {
                  release {
                      isMinifyEnabled = false
                      proguardFiles(
                          getDefaultProguardFile("proguard-android-optimize.txt"),
                          "proguard-rules.pro"
                      )
                  }
                  debug { isMinifyEnabled = false }
              }

              compileOptions {
                  sourceCompatibility = JavaVersion.VERSION_17
                  targetCompatibility = JavaVersion.VERSION_17
              }
              kotlinOptions { jvmTarget = "17" }
          }

          dependencies {
              implementation("androidx.core:core-ktx:1.13.1")
              implementation("androidx.appcompat:appcompat:1.7.0")
              implementation("com.google.android.material:material:1.12.0")
          }
          EOF

          cat > app/proguard-rules.pro <<'EOF'
          # No special rules needed.
          EOF

          cat > app/src/main/AndroidManifest.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <manifest xmlns:android="http://schemas.android.com/apk/res/android"
              package="com.soi.tetris">
              <application
                  android:allowBackup="true"
                  android:icon="@mipmap/ic_launcher"
                  android:label="@string/app_name"
                  android:roundIcon="@mipmap/ic_launcher_round"
                  android:supportsRtl="true"
                  android:theme="@style/Theme.SoiTetris">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:screenOrientation="portrait">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN" />
                          <category android:name="android.intent.category.LAUNCHER" />
                      </intent-filter>
                  </activity>
              </application>
          </manifest>
          EOF

          cat > app/src/main/res/layout/activity_main.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
              android:layout_width="match_parent"
              android:layout_height="match_parent"
              android:background="@color/board_bg">

              <com.soi.tetris.GameView
                  android:id="@+id/gameView"
                  android:layout_width="match_parent"
                  android:layout_height="match_parent" />

          </FrameLayout>
          EOF

          cat > app/src/main/res/values/strings.xml <<'EOF'
          <resources>
              <string name="app_name">Soi&#39;s Tetris</string>
          </resources>
          EOF

          cat > app/src/main/res/values/colors.xml <<'EOF'
          <resources>
              <color name="black">#000000</color>
              <color name="white">#FFFFFF</color>
              <color name="board_bg">#121212</color>
              <color name="text_primary">#FFFFFF</color>
          </resources>
          EOF

          cat > app/src/main/res/values/themes.xml <<'EOF'
          <resources xmlns:tools="http://schemas.android.com/tools">
              <style name="Theme.SoiTetris" parent="Theme.MaterialComponents.DayNight.NoActionBar">
                  <item name="android:statusBarColor">@color/board_bg</item>
                  <item name="android:navigationBarColor">@color/board_bg</item>
                  <item name="android:windowBackground">@color/board_bg</item>
                  <item name="android:windowLayoutInDisplayCutoutMode">shortEdges</item>
              </style>
          </resources>
          EOF

          cat > app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@android:color/black"/>
              <foreground android:drawable="@android:color/white"/>
          </adaptive-icon>
          EOF

          cat > app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml <<'EOF'
          <?xml version="1.0" encoding="utf-8"?>
          <adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">
              <background android:drawable="@android:color/black"/>
              <foreground android:drawable="@android:color/white"/>
          </adaptive-icon>
          EOF

          cat > app/src/main/java/com/soi/tetris/MainActivity.kt <<'EOF'
          package com.soi.tetris

          import android.os.Bundle
          import androidx.appcompat.app.AppCompatActivity

          class MainActivity : AppCompatActivity() {
              override fun onCreate(savedInstanceState: Bundle?) {
                  super.onCreate(savedInstanceState)
                  setContentView(R.layout.activity_main)
              }
          }
          EOF

          cat > app/src/main/java/com/soi/tetris/GameView.kt <<'EOF'
          package com.soi.tetris

          import android.content.Context
          import android.graphics.*
          import android.util.AttributeSet
          import android.view.MotionEvent
          import android.view.SurfaceHolder
          import android.view.SurfaceView
          import kotlin.math.abs
          import kotlin.random.Random

          class GameView @JvmOverloads constructor(
              context: Context, attrs: AttributeSet? = null
          ) : SurfaceView(context, attrs), SurfaceHolder.Callback, Runnable {

              private var thread: Thread? = null
              @Volatile private var running = false

              private val cols = 10
              private val rows = 20
              private val board = Array(rows) { IntArray(cols) { 0 } }
              private var cellSize = 0f
              private var offsetX = 0f
              private var offsetY = 0f

              private val paint = Paint(Paint.ANTI_ALIAS_FLAG)
              private val textPaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
                  color = Color.WHITE
                  textSize = 48f
                  typeface = Typeface.create(Typeface.MONOSPACE, Typeface.BOLD)
              }
              private val titlePaint = Paint(Paint.ANTI_ALIAS_FLAG).apply {
                  color = Color.WHITE
                  textSize = 58f
                  typeface = Typeface.create(Typeface.DEFAULT_BOLD, Typeface.BOLD)
              }

              private val shapes = arrayOf(
                  arrayOf(
                      intArrayOf(0,0,0,0),
                      intArrayOf(1,1,1,1),
                      intArrayOf(0,0,0,0),
                      intArrayOf(0,0,0,0)
                  ),
                  arrayOf(
                      intArrayOf(2,0,0),
                      intArrayOf(2,2,2),
                      intArrayOf(0,0,0)
                  ),
                  arrayOf(
                      intArrayOf(0,0,3),
                      intArrayOf(3,3,3),
                      intArrayOf(0,0,0)
                  ),
                  arrayOf(
                      intArrayOf(4,4),
                      intArrayOf(4,4)
                  ),
                  arrayOf(
                      intArrayOf(0,5,5),
                      intArrayOf(5,5,0),
                      intArrayOf(0,0,0)
                  ),
                  arrayOf(
                      intArrayOf(0,6,0),
                      intArrayOf(6,6,6),
                      intArrayOf(0,0,0)
                  ),
                  arrayOf(
                      intArrayOf(7,7,0),
                      intArrayOf(0,7,7),
                      intArrayOf(0,0,0)
                  )
              )

              private val colors = intArrayOf(
                  Color.TRANSPARENT,
                  Color.parseColor("#00BCD4"),
